### ISSUE TITLE
Inclusion of varnastat methods?

### ISSUE THREAD

**Issue by MartinHinz** [ISAAKiel/quantAAR#1]
Which methods of varnastat should be included, and in which way this should be done?

Options:
- dependency on the package
- Copy code
- Reprogramming of methods

**Comment by nevrome** [comment]
I support the copy+reprogramming option. varnastats needs a lot of love and it's more easy to prepare one package for CRAN than two.

**Comment by MartinHinz** [comment]
In this case, I would assign this task to you... :-)

**Comment by nevrome** [comment]
The copy part is done now - reprogramming and reorganising will be more time consuming.

**Comment by MartinHinz** [comment]
Will assist you with that!

**Comment by MartinHinz** [comment]
I think we archived a good state with that, I will close this issue and treat all the remaining problems as refactoring of the project as such.
