### ISSUE TITLE
Correspondence Analysis and/or related ordination methods

### ISSUE THREAD

**Issue by MartinHinz** [ISAAKiel/quantAAR#3]
Include c(c)a and/or other ordination methods like (N)MDS.

I opt for dependency on [vegan](https://github.com/vegandevs/vegan).

The aim should be to make them more accessible for archaeologists...

**Comment by nevrome** [comment]
IMHO no own implementation of something that's already solved in a good way. 

varnastats depends on library(ca) and even has a interface function for it. But if vegan is better - why not? I just like to have a simple and tidy (!) interface for the ca-function.

**Comment by MartinHinz** [comment]
This functionality might become part of the package, when we have decided, how we would like to proceed with it (#8). Meanwhile, and due to lack of activity on that issue, I currently will close down this issue, knowing that it will pop up one day or the other.
