### ISSUE TITLE
Excavation analysis / working with measurements and 3D data

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/quantAAR#5]
I'm currently working on some tools to work with 3D spatial data within the scope of excavations. This could be part of a bigger effort to provide tools for field archaeologists. Some ideas:
- interfaces for measurement gear (COM-Port)
- analysis and visualization of 3D point distributions
  - measurements
  - SFM 
  - etc.
- raster analysis 
  - SFM pictures quality assesement 
  - semi automatic classification for profile pictures
  - etc.

**Comment by MartinHinz** [comment]
Supercool! I have no experience with SFM inside of R, is it worth competing with standard software like PhotoScan or VisualSFM?

Would add handeling of tachy data. Probably also geomagnetics?

Would it be useful to seperate package purposes? ´quantaar´ for statistical analysis, ´name of additional package´ for dealing with hardware and interfaces?

Excluding auto classification, this would likely fit into ´quantaar´. Have already some ideas and methods for that. But would like to publish them first as paper...

**Comment by nevrome** [comment]
[recexcavAAR](https://github.com/ISAAKiel/recexcavAAR) now includes some spatial tools for excavation contexts. I think we should continue this discussion there.
