### ISSUE TITLE
lintr-bot

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/quantAAR#6]
Should we set up a [lintr-bot](https://github.com/jimhester/lintr) for automatic syntax-correction? 

Never personally worked with it, but I've seen it some times. Facilitates keeping code clean.

**Comment by MartinHinz** [comment]
I use lintr too, but I prefer having manual controll over the results, since lintr do correct from time to time wrongly (just happend: function calls not recognised as such).

**Comment by nevrome** [comment]
Ok - I will look into using it locally.
